"""empty message

Revision ID: a260f8cc715e
Revises: e1b78f6812cd
Create Date: 2020-10-30 00:57:45.666458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a260f8cc715e'
down_revision = 'e1b78f6812cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.add_column('post', sa.Column('role', sa.String(length=30), nullable=True))
    op.drop_column('post', 'content')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=100), nullable=True))
    op.add_column('post', sa.Column('content', sa.VARCHAR(length=300), nullable=True))
    op.drop_column('post', 'role')
    op.drop_column('post', 'phone_number')
    # ### end Alembic commands ###
